### ISSUE TITLE
Keep getting connection error to database

### ISSUE THREAD

**Issue by markatosi** [DevExpress-Examples/gridview-how-to-implement-and-edit-many-to-many-relations-in-mvc-t113290#2]
I see that this example is using what I presume is a local mdf file but the connection string doesn't indicate that. I've tried modifying it but to no avail. I'm using VS 2017 I have SQLExpress installed (2017) and localdb is supposed to be installed by default in VS 2017

**Comment by CodeKarno** [comment]
@markatosi In this example, the database is generated in the [ManyToManyInitializer.cs file, the Seed method](https://github.com/DevExpress-Examples/gridview-how-to-implement-and-edit-many-to-many-relations-in-mvc-t113290/blob/14.1.3%2B/CS/ManyToManySampe/Models/ManyToManyInitializer.cs). The Entity Framework context uses the "DefaultConnection" string to connect to a data server.
According to my results, the project should work in VS 2017. Probably, you may need to run Visual Studio as administrator to elevate access permissions.
If this does not help, please submit a [ticket](https://www.devexpress.com/Support/Center/Question/List/1) to our Support Center and specify the exact error message.
